server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # mysql 8.0.+使用的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1Mb
      max-request-size: 10Mb

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources

  thymeleaf:
      prefix:classpath: /templates
      suffix: .html
  mybatis:
    # mapper映射文件地址，这里我在src/main/resouces下新建文件夹mapper
    #mapper-locations: classpath*:mapper/*.xml
    # 配置bean扫描目录，也可用注解
    type-aliases-package: classpath*:edu.tongji.myblog.entity
    #configuration:
      #map-underscore-to-camel-case: true
